# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
minecraft_version=24w13a
yarn_mappings=24w13a+build.7
loader_version=0.15.7

#Fabric api
fabric_version=0.96.13+1.20.5

# Mod Properties
mod_version = 1.0.0-1.20.5
maven_group = frootloops.versus
archives_base_name = players-versus