# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
minecraft_version=24w19b
yarn_mappings=24w19b+build.2
loader_version=0.15.11

#Fabric api
fabric_version=0.98.1+1.21

# Mod Properties
mod_version = 1.0.0-1.21
maven_group = frootloops.versus
archives_base_name = players-versus