package frootloops.versus.mod.items.inventory.sorting;

public enum ItemType {
    SWORD, PICKAXE, AXE, SHOVEL, HOE,
    SPECIAL_WEAPON, BOW, CROSSBOW, TOTEM, SHIELD,
    SHEARS, FISHING_ROD, COMBAT_ITEMS, SPYGLASS, TORCHES_AND_LANTERNS,
    FOOD,
    CLUTCH_TOOL, MISC_TOOL,
    ITEM_CONTAINER, BLOCK_WORKSTATION,
    BLOCK_FULL, BLOCK_SLAB, BLOCK_STAIRS, BLOCK_WALL, BLOCK_FENCE, BLOCK_OTHER,
    ELYTRA, CHESTPLATE, LEGGINGS, BOOTS, HELMET, ARROWS, SMITHING_TEMPLATE,
    POTIONS, BREWING_INGREDIENT,
    POTTERY, BANNER_PATTERNS, DISCS,
    MISC,
    PLANTS_AND_FLOWERS,
    TRASH
}
