package frootloops.versus.mod.items.inventory.sorting;

public enum ItemType {
    SWORD, PICKAXE, AXE, SHOVEL, HOE, SPECIAL_WEAPON, BOW, CROSSBOW, SHIELD, TOTEM, SHEARS, COMBAT_ITEMS, SPYGLASS, TORCHES_AND_LANTERNS, FOOD, POTIONS, CLUTCH_TOOL, MISC_TOOL, BLOCK_WORKSTATION, BLOCK_FULL, BLOCK_SLAB, BLOCK_STAIRS, BLOCK_WALL, BLOCK_FENCE, BLOCK_OTHER, ELYTRA, CHESTPLATE, LEGGINGS, BOOTS, HELMET, ARROWS, SMITHING_TEMPLATE, BREWING_INGREDIENT, POTTERY, BANNER_PATTERNS, MISC, TRASH
}
