package frootloops.versus.mod.items_and_effects.inventory.sorting;

public enum ItemType {
    SWORD, PICKAXE, AXE, SHOVEL, HOE,
    SPECIAL_WEAPON, BOW, CROSSBOW, TOTEMS, SHIELD,
    SHEARS, FISHING_ROD, COMBAT_ITEMS, SPYGLASS, TORCHES_AND_LANTERNS,
    GAPPLES, FOOD,
    CLUTCH_TOOL, MISC_TOOL,
    BLOCK_WORKSTATION,
    BLOCK_FULL, BLOCK_SLAB, BLOCK_STAIRS, BLOCK_WALL, BLOCK_FENCE, BLOCK_OTHER,
    ELYTRA, CHESTPLATE, LEGGINGS, BOOTS, HELMET, SMITHING_TEMPLATE,
    POTIONS, BREWING_INGREDIENT,
    POTTERY, BANNER_PATTERNS, DISCS,
    MISC,
    PLANTS_AND_FLOWERS,
    ARROWS,
    TRASH,
    ITEM_CONTAINER,
    BUNDLE,
    SHULKER_BOX
}
